# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'MQTTDemo' do
pod 'MQTTClient/Websocket'
pod 'MQTTClient'
end

target 'MQTTDemoTests' do

end

target 'MQTTDemoUITests' do

end

